package Lab8;
import java.awt.*;
import simView.*;

public class air_conditioning_system extends ViewableDigraph
{

	public air_conditioning_system()
	{
		super("air_conditioning_system");
    	
		ViewableAtomic u = new user("user");
		ViewableDigraph a = new air_conditioner("air_conditioner", 10, 10);
    	
		add(u);
		add(a);

		addCoupling(u, "out", a, "in");
	}

    
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(716, 383);
        ((ViewableComponent)withName("air_conditioner")).setPreferredLocation(new Point(163, 68));
        ((ViewableComponent)withName("user")).setPreferredLocation(new Point(23, 93));
    }
}
