package Lab8;
import simView.*;
import java.awt.*;

public class air_conditioner extends ViewableDigraph
{
	
	public air_conditioner()
	{
		this("air_conditioner", 10, 10);
	}
	
	public air_conditioner(String name, double controller_time, double sensor_time)
	{
		super(name);
		
		addInport("in");
		
		ViewableAtomic c = new controller("controller", controller_time);
		ViewableAtomic t = new temp_sensor("temp_sensor");

		add(c);
		add(t);

		addCoupling(this, "in", c, "in1");

		addCoupling(c, "out", t, "in");
		addCoupling(t, "out", c, "in2");
	}

    
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(463, 297);
        ((ViewableComponent)withName("controller")).setPreferredLocation(new Point(44, 44));
        ((ViewableComponent)withName("temp_sensor")).setPreferredLocation(new Point(227, 184));
    }
}
